#+TITLE: Getting Setup -- giving doom emacs a spin ðŸš†
#+DATE:    December 3, 2020
#+SINCE:   <replace with next tagged release version>
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#maintainers][Maintainers]]
  - [[#packages][Packages]]
    - [[#doom][doom]]
    - [[#private][private]]
  - [[#goto-commands][Goto Commands]]
    - [[#spc-i-e-emojify-insert-emoji-][(SPC i e) emojify-insert-emoji ðŸ³]]
    - [[#spc-m-e-e-eval-last-sexp-----][(SPC m e e) eval-last-sexp     ðŸ¥‘]]
    - [[#spc-t-t-treemacs-------------][(SPC t t) treemacs             â›‘]]
    - [[#spc-t-m-minimap-mode---------][(SPC t m) minimap-mode         ðŸ˜]]
    - [[#spc-h-t-load-theme-----------][(SPC h t) load-theme           ðŸ†]]
    - [[#spc-o-t-vterm-here-----------][(SPC o t) vterm-here           ðŸŒˆ]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]
- [[#tips][Tips]]
- [[#episode-1][Episode 1]]
  - [[#doom-doctor--][`doom doctor`  ðŸ‘œ]]
  - [[#doom-sync-][`doom sync` ðŸ™‹ðŸ¾]]
  - [[#migrating-from-spacemacs-][Migrating from spacemacs. â‡]]
  - [[#live-coding-todos-][Live coding TODOS. ðŸ—’]]
  - [[#general-assesment][General Assesment]]
- [[#future-episode-topics][Future Episode Topics]]
  - [[#setup-sql-driver][Setup sql driver]]

* Description
# A plan for making this perfect!

** Maintainers
+ @Lyonsclay (Author)

** Packages
# A list of packages
*** doom
+ treemacs ðŸ˜º
+ lsp ðŸ²
*** private
+ keychord ðŸ€

** Goto Commands
# A list of the best of the best
*** (SPC i e) emojify-insert-emoji ðŸ³
*** (SPC m e e) eval-last-sexp     ðŸ¥‘
*** (SPC t t) treemacs             â›‘
*** (SPC t m) minimap-mode         ðŸ˜
*** (SPC h t) load-theme           ðŸ†
*** (SPC o t) vterm-here           ðŸŒˆ

* Prerequisites
+ for a more comprehensive list https://github.com/ztlevi/doom-config
+ brew install emacs-plus/railwaycat (fullscreen works) -- apparently tty issue effects emacs daemon
+ vterm -- yes you want this ðŸ‘€
+

* Features
# An in-depth list of features, how to use them, and their dependencies.

* Configuration
# How to configure this module, including common problems and how to address them.

* Troubleshooting
# Common issues and their solution, or places to look for help.

* Tips
1. If you use ivy(as I do) then you have to scroll by pressing C-M n or C-M p to see previous or next.

* Episode 1
Test driving Doom emacs ðŸŽ
** `doom doctor`  ðŸ‘œ
Doom comes with a command line interface that is quite nice and enables an easy upgrade experience.
** `doom sync` ðŸ™‹ðŸ¾ 
This command will add/remove packages and update all conigs.
** Migrating from spacemacs. â‡ 
I did not expect to move completely as quick as I did after first looking at doom. The UX is phenomenal and makes me an immediate fan. I see three important aspects that make this product great!
a. It looks great.
   ** so many subtle refinements
b. The configuration is well organized and facilitates uprade and down grade scenarios. I need to experience the ecosystem through some upgrades before I can't really comment on that aspect of doom. But I can say that having designated files and code patterns which separate private config and user installed packaeges from framework packages and their configs.
c. Adding go-run function.
** Live coding TODOS. ðŸ‡¬ðŸ‡³
a. Add a keymap for common activity. (make vterm far right or make magit window far right)
b. Decide keys for multiple-cursors.
b. Record setup for project.
c. Test drive typescript with new pbiviz project.
d. Add :localleader mapped commands to gorepl.
   Restart go-repl.
e. PR for window-move-very-far-right

** General Assesment ðŸ‡¬ðŸ‡¼
Migrating to Doom has caused me to take my emacs-elisp to the next level. This is most likely a result of feature loss.

Doom promotes higher level configuration macros ->  


* Future Episode Topics
** Setup sql driver
0:01:44 
0:01:33

# This popped up when visting a python file.
  

# when installing the latest ipython the package jedi needs to be deprecated to <0.18
# in order to enable tab completion in the terminal.


-- tips and trics
-- --
-- --
-- --
-- --
1. ibuffer - is an easy way to delete any buffer from current window.
   To delete a buffer navigate to it in the list(popup window) user j/k,
   then ender 'd' - label line for deleting. 'x' confirms deleting buffers that
   have been designated with a 'd' delete on their respective line.
   I can't figure out how to display the list of actions and keystrokes. TODO

2. clone-indirect-buffer (SPC b c) and clone-indirect-buffer-other-window (SPC b C) can create a second buffer of a particular file. I am not sure the operational difference of the two. My use case is to have two windows of the same file, but have one completely collapsed showing the function names. Note - you can achieve a similar effect by using treemacs and hitting tab. This might be usefull in setting up two database clients from the same file. I do this often when pulling data from a remote database and storing results in my own local database for further analysis.

3. treemacs-peek (P) from the treemacs window is quite nice, especially with the combination of expanding a file to show functions and types.

4. In order to preview color themes on the fly;
   (SPC h t) to get into the interactive color theme selection interface.
   (M C n) to move to the next selection and view it applied to your open windows.
   (M C p) to move to the previous selection and view it applied to your open windows.
   For normal scrolling (C n) or (C j) to move down and (C p) or (C k) to move up.
